logging:
  level:
    org:
    springframework: error

#postgresql connection staff
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: sardor
    properties:
      hibernate:
        format_sql: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

server:
  error:
    include-message: always
    whitelabel:
      enabled: false
    path: /error

application:
  security:
    jwt:
      secret-key: bGbWqUxYztvCj8FzNO8GuJYY/YzkrU9wGx9+gaGwBo+Dmw0c70GFGZhtp2vw+1uq
      expiration: 86400000
      refresh-token:
        expiration: 604800000




